# Nombre del workflow
name: Automation Workflow

# Trigger, o en que momento o con que accion se va a ejecutar
# Solo se realiza con el push en la rama main, debido a inconvenientes con la dependencia mochareports
on: 
  push:
    branches: main
  schedule:
    - cron: 0 16 * * *

# Lista de trabajos y los pasos que van a realizar
jobs:
  challenge:

    # Version de OS en el que se va a correr
    runs-on: ubuntu-latest 

    steps:
      # Descargar el codigo
      - name: Download code
        uses: actions/checkout@v4

      # Descargar NodeJS
      - name: Download NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci
      - name: Dev dependencies
        run: npm install --dev

      # Usar Cypress
      - name: Cypress run
        run: npm run cy:run
